services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data

  app:
      build: .
      ports:
      - "8000:8000"
      env_file: .env 
      environment:
        REDIS_URL: redis://redis:6379
  
volumes:
  redis_storage: